---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    pod: api
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: {{ .Values.api.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      pod: api
  template:
    metadata:
      name: api
      labels:
        pod: api
    spec:
      containers:
        - name: api
          image: {{ .Values.image }}
          imagePullPolicy: Always
          args: ["api"]
          env:
            - name: GUNICORN_WORKERS
              value: {{ .Values.api.gunicornWorkers | quote }}
            - name: CLAMD_HOST
              value: {{ .Values.api.clamdHost }}
            - name: CLAMD_PORT
              value: {{ .Values.api.clamdPort | quote }}
            - name: WAIT_FOR_CLAMD
              value: {{ .Values.api.waitForClamd | quote }}
          ports:
            - containerPort: 8000
              protocol: TCP
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
          resources:
            requests:
              cpu: {{ .Values.api.requests.cpu }}
              memory: {{ .Values.api.requests.memory }}
            limits:
              cpu: {{ .Values.api.limits.cpu }}
              memory: {{ .Values.api.limits.memory }}
          readinessProbe:
            httpGet:
              path: /version
              port: 8000
            timeoutSeconds: 5
            initialDelaySeconds: 90
            periodSeconds: 30
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /version
              port: 8000
            timeoutSeconds: 5
            initialDelaySeconds: 90
            periodSeconds: 30
            successThreshold: 1

{{- if .Values.api.disruptionBudget }}
---
kind: PodDisruptionBudget
apiVersion: policy/v1beta1
metadata:
  name: api-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      pod: api
{{- end }}